### ISSUE TITLE
[Suggestion] Data Broker Support Would Be Amazing

### ISSUE THREAD

**Issue by wheatbread** [AzerPUG/Core#19]
It would be great to be able to have the option of having the AzerPug Core clicky on a databroker as an alternative to the free-floating button.

**Comment by Arco-Dielhof** [comment]
Sadly, this is not worth either the effort or the extreme amount of size the addon would gain to support a dying and out dated idea/system. Not many people still use data brokers.

The code would double in order to support this properly, without breaking anything, and the alternative of using libraries would almsot quadruple the size of the addon (libraries in WoW are one of the biggest bloats you can imagine, some addons have 1-20 lines of functional code and another 2-3 MB of bloat libraries...)
