### ISSUE TITLE
Adjust CurseForge and GitHub Description

### ISSUE THREAD

**Issue by Arco-Dielhof** [AzerPUG/Core#6]

**Comment by Arco-Dielhof** [comment]
All AddOns include mention of the core in description.

**Comment by royb3** [comment]
Typo: 
All AzerPUG AddOns are stand-alone and as lightweight as possible.
However, some very resource intensive things with AddOns are really nice to have.
In order to provide these extra things, like optimization or combining the AddOns into one bigger one, we have an **optinal**, combined AddOn.
Anyone who uses several of our AddOns, is strongly suggested to use the AzerPUG's Core as well.
This Core AddOn will do several things that are considered an **imporvement** by most people:
- Speed up loading times.
- Register events more efficiently.
- Deal with all the event handling for all AzerPUG AddOns.
- Deal with all the version control for all AzerPUG AddOns.
